### ISSUE TITLE
Get someone other than notriddle to read the ToS

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng.github.io#20]
Make sure it's reasonable.

**Comment by jniles** [comment]
I've taken a look at the ToS and it looks pretty good!  In my view, there are two components missing that I'll add as soon as I get ruby/jekyll installed locally to test:
 1. A date of last update to the ToS or when they are become enforceable.
 2. A default "opt-in" clause such as "any usage of The Service will constitute acceptance of this agreement."  IANAL, but it seems prudent to explicitly state agreement.

**Comment by notriddle** [comment]
Yeah, that all makes sense. Thanks!
