### ISSUE TITLE
Suggestion: Verify the `bors.tech` domain with GitHub

### ISSUE THREAD

**Issue by DilumAluthge** [bors-ng/bors-ng.github.io#81]
Since you own the `bors.tech` domain, it would be pretty quick and easy for you to verify the domain with GitHub. ([https://help.github.com/en/articles/verifying-your-organizations-domain](https://help.github.com/en/articles/verifying-your-organizations-domain))

Doing so gives you a nice green "Verified" badge on the [https://github.com/bors-ng](https://github.com/bors-ng) page. There aren't really any other benefits, but certainly it looks nice to have your organization be "verified".

**Comment by notriddle** [comment]
Okay, that's done.
